version: "3.9"

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - mailhog  # Add this
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # MailHog configuration
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      # Or for nodemailer:
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_SECURE=false

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI port
    restart: always

  frontend:
    build: ../frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo_data: